appName: simple-web-deployment

namespace: default

configmap:
  name: helm-simple-web-deploymentconfigv1.1
  data: 
    CUSTOM_HEADER: "This app was deployed using helm"

image:
  repository: dhana20/demo-app
  name: ""
  tag: latest