kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{.Values.configmap.name}}
  namespace: {{.Values.namespace}}
data:
  BG_COLOR: '#12181b'
  FONT_COLOR: '#000000'
  CUSTOM_HEADER: {{.Values.configmap.data.CUSTOM_HEADER}}